### ISSUE TITLE
Support Linux kernel < 2.6.24

### ISSUE THREAD

**Issue by JanecekPetr** [comoyo/commons#37]
The atatched protoc binaries for Linux are compiled for kernel 2.6.24 and newer. If run on an older kernel, it throws "FATAL: kernel too old" and exits.

While that was released in 2008 and sounds like a decent choice, in my company, we're still running on RHEL5 and even RHEL4 which are based on 2.6.18 (2005) and 2.6.9 (2004). Would it be possible to compile the attached binaries for older kernels too? Or maybe let it be just like it is now, but in case of an error with the default one, download an extended-compatibility protoc and try with that (this might be preferable because the extended-compatibility protoc will be a considerably larger file)...

**Comment by argggh** [comment]
Hm, this is slightly complicated.  The binaries are compiled statically in order to require a minimum in terms of local run-time dependencies, but this in turn fixes the libc code version used to be the one present on the build machine.  Apparently the static version of libc on the release build machine does not support older kernels than 2.6.32. In order to both produce static builds and also include libc code capable of dealing with older kernels, a dedicated libc version would have to be present on the build machine.

I'll see if there are easy ways to statically link with the libraries that may not be present in all execution environments while at the same time linking dynamically to libc.  This is also a bit thorny, as the dynamic dependency needs to allow for run-time linking with the libc versions of RHEL5 and RHEL4...

**Comment by JanecekPetr** [comment]
Yeah, let's drop this. It's a year later, this is not needed for me anymore. Also, RHEL 4 will be EOL'ed in 9 months anyway (while RHEL 5 support will be reduced).
